import type { BusinessMriResponse } from "@boss/types";

function response(questionKey: string, value: unknown): BusinessMriResponse {
  return {
    id: `resp_${questionKey}`,
    orgId: "org_1",
    businessMriId: "mri_1",
    sectionKey: "identity",
    questionKey,
    value,
    answeredAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
  };
}

export const sampleResponses: BusinessMriResponse[] = [
  response("identity.business_name", "Sunny Lawn Care"),
  response("identity.business_type", "landscaping"),
  response("identity.years_operating", 2),
  response("identity.employees", 4),
  response("identity.locations", 1),
  response("customers.customer_types", ["b2c"]),
  response("customers.acquisition_channels", ["referral", "social"]),
  response("customers.repeat_business", 4),
  response("customers.communication", ["phone", "sms"]),
  response("sales.lead_sources", ["referral"]),
  response("sales.follow_up_process", "manual"),
  response("sales.sales_cycle", "days"),
  response("sales.quote_process", "manual_document"),
  response("operations.scheduling", "spreadsheet"),
  response("operations.daily_tasks", "checklist"),
  response("operations.team_responsibilities", "informal"),
  response("operations.process_documentation", false),
  response("finance.revenue_sources", ["services"]),
  response("finance.invoicing", "spreadsheet"),
  response("finance.collections", "manual_reminders"),
  response("finance.expenses", "manual_tracking"),
  response("finance.cash_flow_visibility", 3),
  response("marketing.website", true),
  response("marketing.social_media", ["facebook", "instagram"]),
  response("marketing.email_marketing", false),
  response("marketing.reviews", 4),
  response("marketing.referral_programs", true),
  response("technology.crm", false),
  response("technology.accounting_software", true),
  response("technology.calendar", true),
  response("technology.phone", "personal_cell"),
  response("technology.email", "business_domain"),
  response("technology.existing_ai_usage", false),
  response("goals.priorities", ["growth", "automation"]),
  response("pain_points.challenges", ["missed_leads", "outstanding_invoices"]),
];
